services:
  web:
    image: ghcr.io/ward-smeyers/lws-milestone2-web:main
    ports:
      - 80:80
    tty: true
    depends_on:
      - api
    restart: unless-stopped

  api:
    image: ghcr.io/ward-smeyers/lws-milestone2-api:main
    environment:
      - FRONTEND_URL=http://milestone2.local/
      - BACKEND_URL=http://api.milestone2.local:8080/
      - MONGODB_USERNAME=${MONGODB_INITDB_ROOT_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_INITDB_ROOT_PASSWORD}
      - MONGODB_HOST=db
    ports:
      - 8080:80
    depends_on:
      - db
    restart: unless-stopped
    
  db:
    image: mongodb/mongodb-community-server
    env_file:
      - .env
    restart: unless-stopped
