services:
  web:
    image: sebp/lighttpd # https://github.com/spujadas/lighttpd-docker
    volumes:
      - ./web/index.html:/var/www/localhost/htdocs/index.html
      # - ./web/lighttpd:/etc/lighttpd
    ports:
      - 80:80
    tty: true
    depends_on:
      - api
    restart: unless-stopped

  api:
    build: ./api
    ports:
      - 8080:8080
    volumes:
      - ./api:/api
    depends_on:
      - db
    restart: unless-stopped
    
  db:
    image: mongodb/mongodb-community-server
    volumes:
      - db:/data/db
    env_file:
      - .env
    restart: unless-stopped

volumes:
  db:
    driver: local
