services:
  web:
    build: ./web
    ports:
      - 80:80
    volumes:
      - ./web:/var/www/localhost/htdocs
    tty: true
    depends_on:
      - api
    restart: unless-stopped

  api:
    build: ./api
    environment:
      - FRONTEND_URL=http://milestone2.local
      - MONGODB_USERNAME=${MONGODB_INITDB_ROOT_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_INITDB_ROOT_PASSWORD}
      - MONGODB_HOST=db
    ports:
      - 8080:80
    depends_on:
      - db
    restart: unless-stopped
    
  db:
    image: mongodb/mongodb-community-server
    env_file:
      - .env
    restart: unless-stopped
