services:
  web:
    build: ./web  # Build the web service from the Dockerfile
    ports:
      - 80:80  # Map port 80 of the host to port 80 of the container
    volumes:
      - ./web:/var/www/localhost/htdocs  # Mount the ./web directory to /var/www/localhost/htdocs in the container
    tty: true  # Allocate a pseudo-TTY necessary for the startup script in this image
    depends_on:
      - api  # The web service depends on the api service
    restart: unless-stopped  # Always restart the container unless it is explicitly stopped

  api:
    build: ./api  # Build the api service from the Dockerfile
    environment:
      # Set the FRONTEND_URL environment variable
      - FRONTEND_URL=http://milestone2.local
      # Set the MONGODB_USERNAME environment variable from the .env file
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      # Set the MONGODB_PASSWORD environment variable from the .env file
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      # Set the MONGODB_HOST environment variable to database service name 'db'
      - MONGODB_HOST=db
    ports:
      - 8080:80  # Map port 8080 of the host to port 80 of the container
    depends_on:
      - db  # The api service depends on the db service
    # Always restart the container unless it is explicitly stopped
    restart: unless-stopped
    
  db:
    # Use the mongodb-community-server image for the db service
    image: mongodb/mongodb-community-server
    env_file:
      - .env  # Load environment variables from the .env file
    # Always restart the container unless it is explicitly stopped
    restart: unless-stopped
