
Vagrant.configure("2") do |config|
  config.vm.define "milestone2-master"
  config.vm.box = "generic/ubuntu2204"
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.provider "virtualbox" do |v|
    v.name = "milestone2-master"
    v.memory = 4096
    v.cpus = 4
  end
  
  config.vm.hostname = "milestone2-master"
  config.vm.synced_folder ".", "/kubeadm"
  config.vm.synced_folder "../app", "/app"
  config.vm.provision "shell", path: "./script.sh"
  config.vm.provision "shell", path: "./master.sh"

end

Vagrant.configure("2") do |config|
  config.vm.define "milestone2-worker1"
  config.vm.box = "generic/ubuntu2204"
  config.vm.network "private_network", ip: "192.168.56.11"
  config.vm.provider "virtualbox" do |v|
    v.name = "milestone2-worker1"
    v.memory = 4096
    v.cpus = 4
  end
  
  config.vm.hostname = "milestone2-worker1"
  config.vm.synced_folder ".", "/kubeadm"
  config.vm.synced_folder "../app", "/app"
  config.vm.provision "shell", path: "./script.sh"
  # config.vm.provision "shell", path: "./join-command.sh"

end
